language: node_js
node_js:
  - "8"
  - "10"
  - "12"
dist: xenial
env:
  - NODE_ENV=travis
jobs:
  include:
    - stage: lint
      script: npm run-script lint
    - stage: test
      script: npm run-script test
      # after_script: "npm run coverage"
